/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace InvoiceRegistry {
      
    export type InvoiceStruct = {id: BigNumberish, creator: AddressLike, amount: BigNumberish, createdAt: BigNumberish, status: BigNumberish, payer: AddressLike, paidAt: BigNumberish}

    export type InvoiceStructOutput = [id: bigint, creator: string, amount: bigint, createdAt: bigint, status: bigint, payer: string, paidAt: bigint] & {id: bigint, creator: string, amount: bigint, createdAt: bigint, status: bigint, payer: string, paidAt: bigint }
  
    }

  export interface InvoiceRegistryInterface extends Interface {
    getFunction(nameOrSignature: "createInvoice" | "creatorInvoiceCount" | "getInvoice" | "getInvoicesByCreator" | "payInvoice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "InvoiceCreated" | "InvoicePaid"): EventFragment;

    encodeFunctionData(functionFragment: 'createInvoice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'creatorInvoiceCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getInvoice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getInvoicesByCreator', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'payInvoice', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creatorInvoiceCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvoicesByCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payInvoice', data: BytesLike): Result;
  }

  
    export namespace InvoiceCreatedEvent {
      export type InputTuple = [id: BigNumberish, creator: AddressLike, amount: BigNumberish, createdAt: BigNumberish];
      export type OutputTuple = [id: bigint, creator: string, amount: bigint, createdAt: bigint];
      export interface OutputObject {id: bigint, creator: string, amount: bigint, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoicePaidEvent {
      export type InputTuple = [id: BigNumberish, payer: AddressLike, amount: BigNumberish, paidAt: BigNumberish];
      export type OutputTuple = [id: bigint, payer: string, amount: bigint, paidAt: bigint];
      export interface OutputObject {id: bigint, payer: string, amount: bigint, paidAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InvoiceRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): InvoiceRegistry;
    waitForDeployment(): Promise<this>;

    interface: InvoiceRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createInvoice: TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    creatorInvoiceCount: TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getInvoice: TypedContractMethod<
      [id: BigNumberish, ],
      [InvoiceRegistry.InvoiceStructOutput],
      'view'
    >
    

    
    getInvoicesByCreator: TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    payInvoice: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createInvoice'): TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creatorInvoiceCount'): TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getInvoice'): TypedContractMethod<
      [id: BigNumberish, ],
      [InvoiceRegistry.InvoiceStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getInvoicesByCreator'): TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'payInvoice'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >;

    getEvent(key: 'InvoiceCreated'): TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
getEvent(key: 'InvoicePaid'): TypedContractEvent<InvoicePaidEvent.InputTuple, InvoicePaidEvent.OutputTuple, InvoicePaidEvent.OutputObject>;

    filters: {
      
      'InvoiceCreated(uint256,address,uint256,uint256)': TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
      InvoiceCreated: TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
    

      'InvoicePaid(uint256,address,uint256,uint256)': TypedContractEvent<InvoicePaidEvent.InputTuple, InvoicePaidEvent.OutputTuple, InvoicePaidEvent.OutputObject>;
      InvoicePaid: TypedContractEvent<InvoicePaidEvent.InputTuple, InvoicePaidEvent.OutputTuple, InvoicePaidEvent.OutputObject>;
    
    };
  }