/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { RejectEther, RejectEtherInterface } from "../RejectEther.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "registry",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "createInvoice",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506101858061001c5f395ff3fe608060405260043610610020575f3560e01c8063b095853214610075575f5ffd5b366100715760405162461bcd60e51b815260206004820152601c60248201527f52656a65637445746865723a206e6f2045544820616363657074656400000000604482015260640160405180910390fd5b5f5ffd5b348015610080575f5ffd5b5061009461008f366004610103565b610096565b005b6040516302829def60e31b8152600481018290526001600160a01b03831690631414ef78906024016020604051808303815f875af11580156100da573d5f5f3e3d5ffd5b505050506040513d601f19601f820116820180604052508101906100fe9190610138565b505050565b5f5f60408385031215610114575f5ffd5b82356001600160a01b038116811461012a575f5ffd5b946020939093013593505050565b5f60208284031215610148575f5ffd5b505191905056fea26469706673582212202a107e769a3f72d4d2626dbe5f111e51111d78e21629f5b5bb1d479df6b56f8164736f6c634300081e0033";

  
      type RejectEtherConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: RejectEtherConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class RejectEther__factory extends ContractFactory {
    
      constructor(...args: RejectEtherConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<RejectEther & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): RejectEther__factory {
      return super.connect(runner) as RejectEther__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): RejectEtherInterface {
      return new Interface(_abi) as RejectEtherInterface;
    }
    
    override attach(address: string | Addressable): RejectEther {
      return super.attach(address) as RejectEther;
    }
  static connect(address: string, runner?: ContractRunner | null): RejectEther {
      return new Contract(address, _abi, runner) as unknown as RejectEther;
    }
  }

  
  